name: Integração Contínua

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      run_lint:
        description: "Executar Lint?"
        required: true
        default: true
        type: boolean
      run_tests:
        description: "Executar Testes?"
        required: true
        default: true
        type: boolean

jobs:
  chamar-workflow-lint-e-test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_lint: ${{ inputs.run_lint }}
      run_tests: ${{ inputs.run_tests }}
    secrets: inherit
