name: Hello DevCalc

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Hello Message
        run: echo "Pipeline iniciado com sucesso!"
