name: Reutilizável - Lint e Testes

on:
  workflow_call:
    inputs:
      run_lint:
        required: true
        type: boolean
      run_tests:
        required: true
        type: boolean

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Rodar Lint
        run: mvn checkstyle:check

  tests:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Rodar testes
        run: mvn test