name: secrets-variables

on:
  workflow_dispatch:

jobs:
  variables-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir Variáveis
        run: |
          echo "Modo de execução: ${{ vars.APP_MODE }}"
          echo "Suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular Uso de Token
        run: |
          echo "Autenticando com PROD_TOKEN..."
          echo "Token: ${{ secrets.PROD_TOKEN }}"
